### PR TITLE
Add samtools ampliconstats feature

### PR DESCRIPTION
**Pull request by ac55-sanger**
This feature of samtools is only available in it's development branch, hence it cannot be directly used. I have created a separate repo and updated the info in README.md file on how to build and use conda packages for htslib and samtools from their development branch. 

This pull request also generates ampliconstats per file basis. Will soon add support to run it against all the files in one go.

### CODE REVIEW

**Comment by sb10** [comment]
Since this requires special installation for dev samtools, if that can't be integrated cleanly into this repo, ampliconstats will need to be made an option, so it doesn't break the existing tests.
Ideally a test should be added for ampliconstats mode, if it's possible to run install dev samtools as part of the test script.

**Comment by ac55-sanger** [comment]
Added a parameter under illumina conf to run ampliconstats (samtools development branch) if "--ampliconstats" flag is passed.

**Comment by sb10** [comment]
Thanks @ac55-sanger . Unfortunately the tests are now failing for some reason that doesn't seem related to your changes? It's failing the installation of nextflow using conda.

Can you try and replicate this by running `.github/scripts/install_conda.sh` and then

```
export PATH=/opt/conda/bin:$PATH
conda install -c bioconda nextflow
NXF_VER=20.03.0-edge nextflow -version
```

**Comment by m-bull** [comment]
@sb10 - suggest installing Miniconda3 for tests: https://github.com/connor-lab/ncov2019-artic-nf/commit/319ca24d17d97acd7c74846e0c06e2471e09e166

**Comment by ac55-sanger** [comment]
@sb10 Followed the steps and it fails due to multiple conflicts.

@m-bull 's commit fixes it, just tested:

$NXF_VER=20.03.0-edge nextflow -version
CAPSULE: Downloading dependency io.nextflow:nf-tower:jar:20.03.0-edge
CAPSULE: Downloading dependency io.nextflow:nf-commons:jar:20.03.0-edge
CAPSULE: Downloading dependency io.nextflow:nf-httpfs:jar:20.03.0-edge
CAPSULE: Downloading dependency io.nextflow:nextflow:jar:20.03.0-edge
CAPSULE: Downloading dependency jline:jline:jar:2.14.6
                                        33 KB              
      N E X T F L O W
      version 20.03.0-edge build 5288
      created 28-03-2020 11:10 UTC 
      cite doi:10.1038/nbt.3820
      http://nextflow.io

**Comment by ac55-sanger** [comment]
Added support to run ampliconstats on all the files in one got under:
https://github.com/connor-lab/ncov2019-artic-nf/pull/58

**Pull request closed without merging**
