### PR TITLE
Add Sanger config

### PR DESCRIPTION
**Pull request by sb10**
We run in LSF and local mode, and use ligation, so adding config file.

It has to be included last, or the `params.allowNoprimer` change doesn't work.

### CODE REVIEW

**Comment by sb10** [comment]
I also removed the lsf and slurm configs since they were now redundant.

Please check my additional change to phw.config is correct.

**Comment by m-bull** [comment]
You can supply `--allowNoprimer` as part of the `nextflow run` command if that's helpful - params supplied on the command line take precedence AFAIK.

I did take that section out of `conf/coguk/phw.config` on purpose!

**Comment by sb10** [comment]
> You can supply `--allowNoprimer` as part of the `nextflow run` command if that's helpful - params supplied on the command line take precedence AFAIK.

Problem is that it is set to true in conf/illumina.config, and we need to make it false. Don't know how to do that on the command line.

I've removed the section from phw.config again.

**Comment by m-bull** [comment]
@sb10 - now you've (quite rightly) moved the institutional config include to the end of `nextflow.config`, you can set/override any params in `sanger.config`:

`params.allowNoprimer = false`

**Comment by sb10** [comment]
> @sb10 - now you've (quite rightly) moved the institutional config include to the end of `nextflow.config`, you can set/override any params in `sanger.config`:

Yes. Not sure if we're talking at cross-purposes, but this is already in the PR.

**Pull request merged**
